cmake_minimum_required(VERSION 3.16)
project(MirvkBuntuBuilder VERSION 1.1.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_executable(mirvkbuntu-builder main.cpp)
if(WIN32)
  target_compile_definitions(mirvkbuntu-builder PRIVATE MIRVKBUNTU_BUILDER_WINDOWS=1)
elseif(APPLE)
  target_compile_definitions(mirvkbuntu-builder PRIVATE MIRVKBUNTU_BUILDER_MACOS=1)
else()
  target_compile_definitions(mirvkbuntu-builder PRIVATE MIRVKBUNTU_BUILDER_LINUX=1)
endif()
include(GNUInstallDirs)
install(TARGETS mirvkbuntu-builder RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} BUNDLE DESTINATION .)
